name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    strategy:
      matrix:
        os:
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
    with:
      go-version-file: go.mod
      config-file: .slsa-goreleaser/${{ matrix.os }}.yml
      private-repository: true
